# site settings
title: Marina Íñiguez
subtitle: 
email: marinainiguezcalero@gmail.com
description: 'Artista visual'
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: 
  name: Alejandro Garcia De La Fuente
  url: https://github.com/Alejandro-GDLF
phone: 642 821 290

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

contact:
  - name: email
    svg: envelope.svg
    value: marinainiguezcalero@gmail.com
    link: "mailto:marinainiguezcalero@gmail.com"
    
  - name: phone
    svg: phone.svg
    value: 642 821 290
    link: "tel:+34642821290"
  
  - name: instagram
    svg: instagram.svg
    value: marina_inica
    link: https://www.instagram.com/marina_inica


socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/marina_inica/
  LinkedIn: 
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed
  sourcemap: always

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections_dir: mycollections
collections:
  sculpture:
    output: true
    permalink: /:collection/:name

  performance:
    output: true
    permalink: /:collection/:name
  
  instalation:
    output: true
    permalink: /:collection/:name